export const animation = {
  none: 'none',
  spin: 'spin 1s linear infinite',
  ping: 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite',
  pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
  bounce: 'bounce 1s infinite',
  shock: {
    animation: 'shock',
    transformOrigin: 'center bottom',
  },
  flash: 'flash',
  bubble: 'bubble',
  'rubber-band': 'rubberBand',
  'shake-x': 'shakeX',
  'shake-y': 'shakeY',
  'head-shake': 'headShake 1s ease-in-out',
  swing: {
    animation: 'swing',
    transformOrigin: 'top center',
  },
  tada: 'tada',
  wobble: 'wobble',
  jello: 'jello',
  'heart-beat': 'heartBeat 1s ease-in-out',
  hinge: 'hinge 2s',
  'jack-in': 'jackInTheBox',
  'light-speed-in-left': 'lightSpeedInLeft',
  'light-speed-in-right': 'lightSpeedInRight',
  'light-speed-out-left': 'lightSpeedOutLeft',
  'light-speed-out-right': 'lightSpeedOutRight',
  flip: { animation: 'flip', backfaceVisibility: 'visible' },
  'flip-in-x': { animation: 'flipInX', backfaceVisibility: 'visible' },
  'flip-in-y': { animation: 'flipInY', backfaceVisibility: 'visible' },
  'flip-out-x': { animation: 'flipOutX', backfaceVisibility: 'visible' },
  'flip-out-y': { animation: 'flipOutY', backfaceVisibility: 'visible' },
  'rotate-in': 'rotateIn',
  'rotate-in-down-left': 'rotateInDownLeft',
  'rotate-in-down-right': 'rotateInDownRight',
  'rotate-in-up-left': 'rotateInUpLeft',
  'rotate-in-up-right': 'rotateInUpRight',
  'rotate-out': 'rotateOut',
  'rotate-out-down-left': 'rotateOutDownLeft',
  'rotate-out-down-right': 'rotateOutDownRight',
  'rotate-out-up-left': 'rotateOutUpLeft',
  'rotate-out-up-right': 'rotateOutUpRight',
  'roll-in': 'rollIn',
  'roll-out': 'rollOut',
  'zoom-in': 'zoomIn',
  'zoom-in-down': 'zoomInDown',
  'zoom-in-left': 'zoomInLeft',
  'zoom-in-right': 'zoomInRight',
  'zoom-in-up': 'zoomInUp',
  'bounce-in': 'bounceIn 750ms',
  'bounce-in-down': 'bounceInDown',
  'bounce-in-left': 'bounceInLeft',
  'bounce-in-right': 'bounceInRight',
  'bounce-in-up': 'bounceInUp',
  'bounce-out': 'bounceOut 750ms',
  'bounce-out-down': 'bounceOutDown',
  'bounce-out-left': 'bounceOutLeft',
  'bounce-out-right': 'bounceOutRight',
  'bounce-out-up': 'bounceOutUp',
  'zoom-out': 'zoomOut',
  'zoom-out-down': 'zoomOutDown',
  'zoom-out-left': 'zoomOutLeft',
  'zoom-out-right': 'zoomOutRight',
  'zoom-out-up': 'zoomOutUp',
  'slide-in-down': 'slideInDown',
  'slide-in-left': 'slideInLeft',
  'slide-in-right': 'slideInRight',
  'slide-in-up': 'slideInUp',
  'slide-out-down': 'slideOutDown',
  'slide-out-left': 'slideOutLeft',
  'slide-out-right': 'slideOutRight',
  'slide-out-up': 'slideOutUp',
  'fade-in': 'fadeIn',
  'fade-in-down': 'fadeInDown',
  'fade-in-down-big': 'fadeInDownBig',
  'fade-in-left': 'fadeInLeft',
  'fade-in-left-big': 'fadeInLeftBig',
  'fade-in-right': 'fadeInRight',
  'fade-in-right-big': 'fadeInRightBig',
  'fade-in-up': 'fadeInUp',
  'fade-in-up-big': 'fadeInUpBig',
  'fade-in-top-left': 'fadeInTopLeft',
  'fade-in-top-right': 'fadeInTopRight',
  'fade-in-bottom-left': 'fadeInBottomLeft',
  'fade-in-bottom-right': 'fadeInBottomRight',
  'fade-out': 'fadeOut',
  'fade-out-down': 'fadeOutDown',
  'fade-out-down-big': 'fadeOutDownBig',
  'fade-out-left': 'fadeOutLeft',
  'fade-out-left-big': 'fadeOutLeftBig',
  'fade-out-right': 'fadeOutRight',
  'fade-out-right-big': 'fadeOutRightBig',
  'fade-out-up': 'fadeOutUp',
  'fade-out-up-big': 'fadeOutUpBig',
  'back-in-up': 'backInUp',
  'back-in-down': 'backInDown',
  'back-in-left': 'backInLeft',
  'back-in-right': 'backInRight',
  'back-out-up': 'backOutUp',
  'back-out-down': 'backOutDown',
  'back-out-left': 'backOutLeft',
  'back-out-right': 'backOutRight',
};

export const animationDuration = {
  DEFAULT: '1000ms',
  75: '75ms',
  100: '100ms',
  150: '150ms',
  200: '200ms',
  300: '300ms',
  500: '500ms',
  700: '700ms',
  1000: '1000ms',
  1500: '1500ms',
  2000: '2000ms',
  2500: '2500ms',
  3000: '3000ms',
};

export const animationDelay = {
  DEFAULT: '500ms',
  75: '75ms',
  100: '100ms',
  150: '150ms',
  200: '200ms',
  300: '300ms',
  500: '500ms',
  700: '700ms',
  1000: '1000ms',
  1500: '1500ms',
  2000: '2000ms',
  2500: '2500ms',
  3000: '3000ms',
};

export const animationIterationCount = {
  DEFAULT: '1',
  loop: 'infinite',
  'repeat-1': '1',
  'repeat-2': '2',
  'repeat-3': '3',
  'repeat-4': '4',
  'repeat-5': '5',
  'repeat-6': '6',
  'repeat-7': '7',
  'repeat-8': '8',
  'repeat-9': '9',
  'repeat-10': '10',
  'repeat-11': '11',
  'repeat-12': '12',
};

export const animationTimingFunction = {
  DEFAULT: 'ease',
  linear: 'linear',
  in: 'ease-in',
  out: 'ease-out',
  'in-out': 'ease-in-out',
};