export const pseudoClassNames = [
  'hover',
  'focus',
  'active',
  'visited',
  'link',
  'target',
  'focus-visible',
  'focus-within',
  'checked',
  'default',
  'disabled',
  'enabled',
  'indeterminate',
  'invalid',
  'valid',
  'optional',
  'required',
  'placeholder-shown',
  'read-only',
  'read-write',
  'first-of-type',
  'last-of-type',
  'only-child',
  'only-of-type',
  'root',
  'empty',
];

export const variantOrder = [
  ...pseudoClassNames,
  'not-checked',
  'not-disabled',
  'not-first-of-type',
  'not-last-of-type',
  'first',
  'not-first',
  'last',
  'not-last',
  'not-only-child',
  'not-only-of-type',
  'even',
  'odd',
  'even-of-type',
  'odd-of-type',
  'before',
  'after',
  'first-letter',
  'first-line',
  'file-selector-button',
  'file',
  'selection',
  'marker',
  'svg',
  'all',
  'children',
  'siblings',
  'sibling',
  'ltr',
  'rtl',
  ...pseudoClassNames.map(pseudoClassName => `group-${pseudoClassName}`),
  'motion-safe',
  'motion-reduce',
  ...pseudoClassNames.map(pseudoClassName => `peer-${pseudoClassName}`),
  ...pseudoClassNames.map(pseudoClassName => `peer-not-${pseudoClassName}`),
];