import {
  breakpoints,
  caretColor,
  caretOpacity,
  backdropBlur,
  backdropBrightness,
  backdropContrast,
  backdropGrayscale,
  backdropHueRotate,
  backdropInvert,
  backdropOpacity,
  backdropSaturate,
  backdropSepia,
  animation,
  animationDelay,
  animationDuration,
  animationIterationCount,
  animationTimingFunction,
  backgroundColor,
  backgroundImage,
  backgroundOpacity,
  backgroundPosition,
  backgroundSize,
  blur,
  borderColor,
  borderOpacity,
  borderRadius,
  borderWidth,
  boxShadow,
  boxShadowColor,
  brightness,
  contrast,
  columns,
  content,
  cursor,
  defaultColors,
  divideColor,
  divideOpacity,
  divideWidth,
  dropShadow,
  fontFamily,
  fontSize,
  fontWeight,
  flex,
  flexGrow,
  flexShrink,
  fill,
  grayscale,
  gap,
  gradientColorStops,
  gridAutoColumns,
  gridAutoRows,
  gridColumn,
  gridColumnEnd,
  gridColumnStart,
  gridRow,
  gridRowEnd,
  gridRowStart,
  gridTemplateColumns,
  gridTemplateRows,
  hueRotate,
  invert,
  letterSpacing,
  lineHeight,
  listStyleType,
  minHeight,
  minWidth,
  objectPosition,
  opacity,
  order,
  outlineColor,
  outlineOffset,
  outlineWidth,
  orientation,
  padding,
  perspectiveOrigin,
  placeholderColor,
  placeholderOpacity,
  ringColor,
  ringOffsetColor,
  ringOffsetWidth,
  ringOpacity,
  ringWidth,
  rotate,
  scale,
  saturate,
  sepia,
  spacing,
  space,
  skew,
  stroke,
  strokeDashArray,
  strokeDashOffset,
  strokeWidth,
  tabSize,
  tShirtScale,
  textColor,
  textDecorationColor,
  textDecorationLength,
  textDecorationOffset,
  textDecorationOpacity,
  textDecorationThickness,
  textIndent,
  textOpacity,
  textShadow,
  textStrokeColor,
  textStrokeWidth,
  transitionDelay,
  transitionDuration,
  transitionProperty,
  transitionTimingFunction,
  transformOrigin,
  variantOrder,
  zIndex,
} from '../../packages-presets/preset-mini/src';
import { keyframes } from '../../packages-presets/preset-mini/src/theme/keyframes';
import plugin from '../../plugin';
import type { Config } from '../../interfaces';

export { defaultColors, tShirtScale } from '../../packages-presets/preset-mini/src';

export const baseConfig: Config = {
  // purge: [],
  presets: [],
  prefixer: true,
  attributify: false,
  darkMode: 'class', // or 'media'
  theme: {
    orientation,
    screens: breakpoints,
    colors: defaultColors,
    spacing,
    animation,
    animationDuration,
    animationDelay,
    animationIterationCount,
    animationTimingFunction,
    backdropBlur,
    backdropBrightness,
    backdropContrast,
    backdropGrayscale,
    backdropHueRotate,
    backdropInvert,
    backdropOpacity,
    backdropSaturate,
    backdropSepia,
    backgroundColor,
    backgroundImage,
    backgroundOpacity,
    backgroundPosition,
    backgroundSize,
    blur,
    borderColor,
    borderOpacity,
    borderRadius,
    borderWidth,
    boxShadow,
    boxShadowColor,
    brightness,
    contrast,
    caretColor,
    caretOpacity,
    columns,
    container: {},
    content,
    cursor,
    divideColor,
    divideOpacity,
    divideWidth,
    dropShadow,
    fill,
    flex,
    flexGrow,
    flexShrink,
    fontFamily,
    fontSize,
    fontWeight,
    gap,
    gradientColorStops,
    gridAutoColumns,
    gridAutoRows,
    gridColumn,
    gridColumnEnd,
    gridColumnStart,
    gridRow,
    gridRowStart,
    gridRowEnd,
    gridTemplateColumns,
    gridTemplateRows,
    height: (theme, { breakpoints }) => ({
      ...(theme('spacing') ?? {}),
      ...tShirtScale,
      '1/2': '50%',
      '1/3': '33.333333%',
      '2/3': '66.666667%',
      '1/4': '25%',
      '2/4': '50%',
      '3/4': '75%',
      '1/5': '20%',
      '2/5': '40%',
      '3/5': '60%',
      '4/5': '80%',
      '1/6': '16.666667%',
      '2/6': '33.333333%',
      '3/6': '50%',
      '4/6': '66.666667%',
      '5/6': '83.333333%',
      // fraction -> percent
      auto: 'auto',
      full: '100%',
      min: 'min-content',
      max: 'max-content',
      prose: '65ch',
      screen: '100vh',
      ...breakpoints(theme('screens') ?? {}),
    }),
    inset: (theme, { negative }) => ({
      auto: 'auto',
      ...(theme('spacing') ?? {}),
      ...negative(theme('spacing')),
      '1/2': '50%',
      '1/3': '33.333333%',
      '2/3': '66.666667%',
      '1/4': '25%',
      '2/4': '50%',
      '3/4': '75%',
      full: '100%',
      '-1/2': '-50%',
      '-1/3': '-33.333333%',
      '-2/3': '-66.666667%',
      '-1/4': '-25%',
      '-2/4': '-50%',
      '-3/4': '-75%',
      '-full': '-100%',
      // fraction -> percent
      // ...negative
    }),
    keyframes,
    letterSpacing,
    lineHeight,
    listStyleType,
    margin: (theme, { negative }) => ({
      auto: 'auto',
      ...(theme('spacing') ?? {}),
      ...negative(theme('spacing')),
      // ...negative
    }),
    maxHeight: (theme, { breakpoints }) => ({
      ...breakpoints(theme('screens') ?? {}),
      ...(theme('spacing') ?? {}),
      ...tShirtScale,
      none: 'none',
      full: '100%',
      min: 'min-content',
      max: 'max-content',
      prose: '65ch',
      screen: '100vh',
    }),
    maxWidth: (theme, { breakpoints }) => ({
      ...breakpoints(theme('screens') ?? {}),
      ...(theme('spacing') ?? {}),
      ...tShirtScale,
      none: 'none',
      full: '100%',
      min: 'min-content',
      max: 'max-content',
      prose: '65ch',
      screen: '100vw',
    }),
    minHeight,
    minWidth,
    objectPosition,
    opacity,
    order,
    outlineColor,
    outlineWidth,
    outlineOffset,
    padding,
    perspective: (theme) => ({
      ...(theme('spacing') ?? {}),
      ...tShirtScale,
      none: 'none',
    }),
    perspectiveOrigin,
    placeholderColor,
    placeholderOpacity,
    ringColor,
    ringOffsetColor,
    ringOffsetWidth,
    ringOpacity,
    ringWidth,
    rotate,
    scale,
    skew,
    space,
    stroke,
    strokeWidth,
    strokeDashArray,
    strokeDashOffset,
    tabSize,
    textColor,
    textOpacity,
    textShadow,
    textDecorationColor,
    textDecorationOpacity,
    textDecorationLength,
    textDecorationOffset,
    textDecorationThickness,
    textIndent,
    textStrokeColor,
    textStrokeWidth,
    transformOrigin,
    transitionDuration,
    transitionDelay,
    transitionProperty,
    transitionTimingFunction,
    translate: (theme, { negative }) => ({
      ...(theme('spacing') ?? {}),
      ...negative(theme('spacing')),
      '1/2': '50%',
      '1/3': '33.333333%',
      '2/3': '66.666667%',
      '1/4': '25%',
      '2/4': '50%',
      '3/4': '75%',
      full: '100%',
      '-1/2': '-50%',
      '-1/3': '-33.333333%',
      '-2/3': '-66.666667%',
      '-1/4': '-25%',
      '-2/4': '-50%',
      '-3/4': '-75%',
      '-full': '-100%',
      // fraction -> percent
      // ...negative
    }),
    width: (theme, { breakpoints }) => ({
      ...(theme('spacing') ?? {}),
      ...tShirtScale,
      // fraction -> percent
      '1/2': '50%',
      '1/3': '33.333333%',
      '2/3': '66.666667%',
      '1/4': '25%',
      '2/4': '50%',
      '3/4': '75%',
      '1/5': '20%',
      '2/5': '40%',
      '3/5': '60%',
      '4/5': '80%',
      '1/6': '16.666667%',
      '2/6': '33.333333%',
      '3/6': '50%',
      '4/6': '66.666667%',
      '5/6': '83.333333%',
      '1/12': '8.333333%',
      '2/12': '16.666667%',
      '3/12': '25%',
      '4/12': '33.333333%',
      '5/12': '41.666667%',
      '6/12': '50%',
      '7/12': '58.333333%',
      '8/12': '66.666667%',
      '9/12': '75%',
      '10/12': '83.333333%',
      '11/12': '91.666667%',
      auto: 'auto',
      full: '100%',
      min: 'min-content',
      max: 'max-content',
      prose: '65ch',
      screen: '100vw',
      ...breakpoints(theme('screens') ?? {}),
    }),
    zIndex,
  },
  variantOrder: variantOrder,
  plugins: [
    plugin(({ addUtilities }) => {
      addUtilities({
        '.before\\:contents': {
          '&::before': {
            content: '""',
            display: 'contents',
          },
        },
        '.after\\:contents': {
          '&::after': {
            content: '""',
            display: 'contents',
          },
        },
      });
    }),
  ],
  handlers: {
    static: true,
    time: true,
    color: true,
    opacity: true,
    number: true,
    string: true,
    bracket: true,
    hex: true,
    nxl: true,
    fraction: true,
    size: true,
    variable: true,
    negative: true,
  },
};
